import shutil
from pathlib import Path


RUNTIME_ROOT_FILES = {
    "pytest.ini": """[pytest]
pythonpath = .
testpaths = src/tests
python_files = test_*.py
addopts = -ra
""",
    ".gitignore": """.venv/
__pycache__/
.pytest_cache/
.mypy_cache/
*.pyc
""",
    "requirements.txt": """pytest
selenium
""",
    "README.md": """# Generated Selenium Pytest Project

This repository was generated by the Katalon test migrator.

## Setup

```powershell
python -m venv .venv
.venv\\Scripts\\Activate.ps1
python -m pip install -r requirements.txt
```

## Run tests

```powershell
pytest
```

## Project structure

- `src/tests`: generated pytest test modules
- `src/object_repository`: converted Katalon object repository files
- `src/profiles/global_variables.py`: generated global variable definitions
- `src/utils`: runtime helper modules used by generated tests
- `src/runtime`: copied runtime utilities from the migrator
- `data`: copied data files referenced by generated tests
""",
}


def copy_runtime_files(destination_root: str) -> None:
    """
    Copy runtime utility files from the migrator into the destination project.
    These files are needed at runtime for the generated tests to function.

    Source → destination mapping:
        src/runtime/base_test.py          → destination/src/runtime/base_test.py
        src/runtime/katalon_helpers.py    → destination/src/runtime/katalon_helpers.py

    Args:
        destination_root: Root folder of the destination project.
    """
    src_root = Path(__file__).resolve().parent.parent  # katalon-test-migrator/src/
    destination_root_path = Path(destination_root)

    file_map = [
        (src_root / "runtime" / "base_test.py",       destination_root_path / "src" / "runtime"),
        (src_root / "runtime" / "katalon_helpers.py", destination_root_path / "src" / "runtime"),
    ]

    copied_count = 0
    for src_file, dest_folder in file_map:
        if not src_file.exists():
            print(f"Warning: source file not found: {src_file}")
            continue
        dest_folder.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_file, dest_folder / src_file.name)
        copied_count += 1
        init_file = dest_folder / "__init__.py"
        if not init_file.exists():
            init_file.touch()

    root_file_count = 0
    for file_name, content in RUNTIME_ROOT_FILES.items():
        destination_file = destination_root_path / file_name
        destination_file.write_text(content, encoding="utf-8")
        root_file_count += 1

    print(f"Runtime: {copied_count} files copied, {root_file_count} root config files created")


def copy_data_files(source_root: str, dest_root: str) -> None:
    """
    Read .dat files from source_root/Data Files, extract dataSourceUrl paths,
    follow those paths, and copy the referenced files to dest_root/data.
    
    Args:
        source_root: Root folder of the source project
        dest_root: Root folder of the destination project
    """
    import xmltodict
    
    data_files_folder = Path(source_root) / "Data Files"
    destination_data_folder = Path(dest_root) / "data"

    if not data_files_folder.exists():
        print(f"Warning: {data_files_folder} not found")
        return

    destination_data_folder.mkdir(parents=True, exist_ok=True)

    copied_count = 0
    warning_count = 0

    for dat_file in data_files_folder.glob("*.dat"):
        try:
            with open(dat_file, "r", encoding="utf-8") as f:
                xml_content = f.read()

            data_dict = xmltodict.parse(xml_content)
            datasource_url = _extract_datasource_url(data_dict)

            if datasource_url:
                # Resolve the path - could be relative to source_root or absolute
                referenced_file = (
                    Path(source_root) / datasource_url
                    if not Path(datasource_url).is_absolute()
                    else Path(datasource_url)
                )

                if referenced_file.exists() and referenced_file.is_file():
                    dest_file = destination_data_folder / referenced_file.name
                    shutil.copy2(referenced_file, dest_file)
                    copied_count += 1
                else:
                    print(f"Warning: Referenced file not found: {referenced_file}")
                    warning_count += 1
            else:
                print(f"Warning: No dataSourceUrl found in {dat_file.name}")
                warning_count += 1

        except Exception as e:
            print(f"Error processing {dat_file}: {e}")
            warning_count += 1

    print(f"Data files: {copied_count} copied, {warning_count} warnings")


def _extract_datasource_url(data_dict):
    """Recursively search for dataSourceUrl in a nested dictionary."""
    if isinstance(data_dict, dict):
        if "dataSourceUrl" in data_dict:
            return data_dict["dataSourceUrl"]
        for value in data_dict.values():
            result = _extract_datasource_url(value)
            if result:
                return result
    elif isinstance(data_dict, list):
        for item in data_dict:
            result = _extract_datasource_url(item)
            if result:
                return result
    return None
