import shutil
from pathlib import Path


RUNTIME_ROOT_FILES = {
    "pytest.ini": """[pytest]
pythonpath = .
testpaths = src/tests
python_files = test_*.py
addopts = -ra
""",
    ".gitignore": """.venv/
__pycache__/
.pytest_cache/
.mypy_cache/
*.pyc
""",
    "requirements.txt": """attrs==26.1.0
certifi==2026.6.17
cffi==2.1.0
colorama==0.4.6
h11==0.16.0
idna==3.18
iniconfig==2.3.0
outcome==1.3.0.post0
packaging==26.2
pluggy==1.6.0
pycparser==3.0
Pygments==2.20.0
PySocks==1.7.1
pytest==9.1.1
selenium==4.46.0
sniffio==1.3.1
sortedcontainers==2.4.0
trio==0.33.0
trio-websocket==0.12.2
typing_extensions==4.16.0
urllib3==2.7.0
websocket-client==1.9.0
wsproto==1.3.2
xmltodict==1.0.4
""",
    "README.md": """# Generated Selenium Pytest Project

This repository was generated by the Katalon test migrator.

## Setup

```powershell
python -m venv .venv
.venv\\Scripts\\Activate.ps1
python -m pip install -r requirements.txt
```

## Run tests

```powershell
pytest
```

## Configure VS Code test discovery (optional)

If you use VS Code, create `.vscode/settings.json` in the generated project and add:

```json
{
    "python.testing.pytestArgs": [
        "src"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true
}
```

Then run `Python: Discover Tests` from the command palette.

## Git ignore behavior

When the migrator creates root configuration files, an existing `.gitignore` is never overwritten.
Missing default Python ignore entries are appended automatically.

## Project structure

- `src/tests`: generated pytest test modules
- `src/object_repository`: converted Katalon object repository files
- `src/profiles/global_variables.py`: generated global variable definitions
- `src/runtime`: copied runtime utilities from the migrator
- `data`: copied data files referenced by generated tests
""",
}


def copy_runtime_files(destination_root: str) -> None:
    """
    Copy runtime utility files from the migrator into the destination project.
    These files are needed at runtime for the generated tests to function.

    Source → destination mapping:
        src/runtime/base_test.py          → destination/src/runtime/base_test.py
        src/runtime/katalon_helpers.py    → destination/src/runtime/katalon_helpers.py

    Args:
        destination_root: Root folder of the destination project.
    """
    src_root = Path(__file__).resolve().parent.parent  # katalon-test-migrator/src/
    destination_root_path = Path(destination_root)

    # Ensure base src/ directory have __init__.py
    src_dir = destination_root_path / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    (src_dir / "__init__.py").touch()

    file_map = [
        (src_root / "runtime" / "base_test.py.template",       destination_root_path / "src" / "runtime"),
        (src_root / "runtime" / "katalon_helpers.py.template", destination_root_path / "src" / "runtime"),
    ]

    copied_count = 0
    for src_file, dest_folder in file_map:
        if not src_file.exists():
            print(f"Warning: source file not found: {src_file}")
            continue
        dest_folder.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_file, dest_folder / src_file.name.removesuffix(".template"))
        copied_count += 1
        init_file = dest_folder / "__init__.py"
        if not init_file.exists():
            init_file.touch()

    root_file_count = 0
    merged_gitignore_count = 0
    unchanged_gitignore_count = 0
    for file_name, content in RUNTIME_ROOT_FILES.items():
        destination_file = destination_root_path / file_name

        if file_name == ".gitignore" and destination_file.exists():
            existing_text = destination_file.read_text(encoding="utf-8")
            existing_lines = existing_text.splitlines()
            existing_entries = {line.strip() for line in existing_lines if line.strip()}

            missing_lines = [
                line for line in content.splitlines()
                if line.strip() and line.strip() not in existing_entries
            ]

            if missing_lines:
                append_block = "\n".join(missing_lines) + "\n"
                separator = "" if not existing_text or existing_text.endswith("\n") else "\n"
                destination_file.write_text(existing_text + separator + append_block, encoding="utf-8")
                merged_gitignore_count += 1
                root_file_count += 1
            else:
                unchanged_gitignore_count += 1
            continue

        destination_file.write_text(content, encoding="utf-8")
        root_file_count += 1

    print(
        f"Runtime: {copied_count} files copied, {root_file_count} root config files created, "
        f"{merged_gitignore_count} existing .gitignore merged, "
        f"{unchanged_gitignore_count} existing .gitignore unchanged"
    )


def copy_data_files(source_root: str, dest_root: str) -> None:
    """
    Read .dat files from source_root/Data Files, extract dataSourceUrl paths,
    follow those paths, and copy the referenced files to dest_root/data.
    
    Args:
        source_root: Root folder of the source project
        dest_root: Root folder of the destination project
    """
    import xmltodict
    
    data_files_folder = Path(source_root) / "Data Files"
    destination_data_folder = Path(dest_root) / "data"

    if not data_files_folder.exists():
        print(f"Warning: {data_files_folder} not found")
        return

    destination_data_folder.mkdir(parents=True, exist_ok=True)

    copied_count = 0
    warning_count = 0

    for dat_file in data_files_folder.glob("*.dat"):
        try:
            with open(dat_file, "r", encoding="utf-8") as f:
                xml_content = f.read()

            data_dict = xmltodict.parse(xml_content)
            datasource_url = _extract_datasource_url(data_dict)

            if datasource_url:
                # Resolve the path - could be relative to source_root or absolute
                referenced_file = (
                    Path(source_root) / datasource_url
                    if not Path(datasource_url).is_absolute()
                    else Path(datasource_url)
                )

                if referenced_file.exists() and referenced_file.is_file():
                    dest_file = destination_data_folder / referenced_file.name
                    shutil.copy2(referenced_file, dest_file)
                    copied_count += 1
                else:
                    print(f"Warning: Referenced file not found: {referenced_file}")
                    warning_count += 1
            else:
                print(f"Warning: No dataSourceUrl found in {dat_file.name}")
                warning_count += 1

        except Exception as e:
            print(f"Error processing {dat_file}: {e}")
            warning_count += 1

    print(f"Data files: {copied_count} copied, {warning_count} warnings")


def _extract_datasource_url(data_dict):
    """Recursively search for dataSourceUrl in a nested dictionary."""
    if isinstance(data_dict, dict):
        if "dataSourceUrl" in data_dict:
            return data_dict["dataSourceUrl"]
        for value in data_dict.values():
            result = _extract_datasource_url(value)
            if result:
                return result
    elif isinstance(data_dict, list):
        for item in data_dict:
            result = _extract_datasource_url(item)
            if result:
                return result
    return None
