name: build-pdf
on: push
jobs:
  compile: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v7
      - name: setup-typst
        uses: typst-community/setup-typst@v5
      - name: compile_pdf
        run: typst compile thesis/Bachelorarbeit.typ thesis/Bachelorarbeit.pdf
      - name: upload_pdf
        uses: actions/upload-artifact@v4
        with:
          name: Bachelorarbeit
          path: thesis/Bachelorarbeit.pdf
        